language: python

services:
  - docker

env:
  global:
    - LATEST_VERSION=9.6
  matrix:
    - VERSION=9.6
    - VERSION=9.5
    - VERSION=9.4
    - VERSION=9.3
    - VERSION=9.2

script:
  - cd ./$VERSION
  - make && make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make VERSION="$VERSION-$TRAVIS_TAG" release
    fi

    if [ "$VERSION" == "$LATEST_VERSION" ]; then
      make VERSION=latest release
    fi
  fi

after_failure:
  - make logs
