language: bash

services:
  - docker

env:
  matrix:
    - POSTGRES_VER=10.4 TAGS=10.4,10,latest
    - POSTGRES_VER=9.6.9 TAGS=9.6,9
    - POSTGRES_VER=9.5.13 TAGS=9.5
    - POSTGRES_VER=9.4.18 TAGS=9.4
    - POSTGRES_VER=9.3.23 TAGS=9.3

script:
  - set -e
  - make compare-orig-configs
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
